name: mern-jenkins

services:
  backend:
    build:
      context: ./server
    ports:
      - "3002:3002"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  jenkins:
    image: trion/jenkins-docker-client
    privileged: true
    user: root
    ports:
      - "8082:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - type: bind
        source: //var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  mongo-data:
  jenkins_home:
